# Generated by Django 6.0.4 on 2026-05-18 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealerreview',
            old_name='review',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='dealerreview',
            name='dealer',
        ),
        migrations.AddField(
            model_name='dealerreview',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ghr.property'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='ghr.property'),
        ),
    ]
