# Generated by Django 6.0.4 on 2026-05-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghr', '0002_rename_review_dealerreview_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerreview',
            name='rating',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
