# Generated by Django 6.0.4 on 2026-06-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghr', '0004_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='profile_picture',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='property',
            name='featured_image',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
