# Generated by Django 6.0.4 on 2026-06-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghr', '0005_alter_dealer_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='profile_picture',
            field=models.ImageField(upload_to='dealers/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='featured_image',
            field=models.ImageField(upload_to='properties/'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to='property_images/'),
        ),
    ]
