# Generated by Django 6.0.4 on 2026-06-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghr', '0007_dealer_agency_name_dealer_city_dealer_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='profile_picture',
            field=models.ImageField(blank=True, default='', max_length=500, upload_to=''),
        ),
    ]
