# Generated by Django 6.0.4 on 2026-06-04 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghr', '0008_alter_dealer_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='agency_name',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='social_youtube',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='website',
        ),
    ]
